# Get base image

FROM node:20-alpine

# Set working directory

WORKDIR /app

# copy the files
COPY . .

#run the app
CMD ["node","index.js"]

# this command run on the termianal
# <docker build -t my-first-image .> 


# To check the image
# <docker images>

# create a container
# <docker run  my-first-image>


